# Pre Processing Notebook
* plan to preprocess data for label encoding even
though the data is not ordinal; because I plan to use this for random forest regresoor and
another tree algorithm
* will also think about encoding in one-hot encoding and then perform knn

In [29]:
# import packages

import numpy as np
import pandas as pd
import seaborn as sns
import sys
import os
import matplotlib.pyplot as plt
import klib
import plotly.figure_factory as ff
from IPython.core.display import display
from scipy import stats
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.metrics import confusion_matrix, plot_confusion_matrix
import joblib
# pd.set_option('display.max_columns', None)
# pd.reset_option('max_rows')
#np.set_printoptions(threshold=sys.maxsize)

plt.style.use('dark_background')
plt.rcParams.update({"grid.linewidth":0.5, "grid.alpha":0.5})
sns.set(style='ticks', context='talk')

In [30]:
# load dataset

df_path = r'../../data/processed/mushroom_imputed_2_adj.csv'
mushroom = pd.read_csv(df_path)

mushroom

Class Cap-Shape Cap-Surface Cap-Color  Bruises     Odor  \
0     poisonous    convex      smooth     brown  bruises  pungent   
1        edible    convex      smooth    yellow  bruises   almond   
2        edible      bell      smooth     white  bruises    anise   
3     poisonous    convex       scaly     white  bruises  pungent   
4        edible    convex      smooth      gray       no     none   
...         ...       ...         ...       ...      ...      ...   
8107     edible    convex      smooth     brown       no     none   
8108     edible      flat      smooth     brown       no     none   
8109  poisonous   knobbed       scaly     brown       no    fishy   
8110     edible    convex      smooth     brown       no     none   
8111     edible   knobbed      smooth     white       no     none   

     Gill-Attachment Gill-Spacing Gill-Size Gill-Color  ...  \
0               free        close    narrow      black  ...   
1               free        close     broad      black  ...   
2               free        close     broad      brown  ...   
3               free        close    narrow      brown  ...   
4               free      crowded     broad      black  ...   
...              ...          ...       ...        ...  ...   
8107        attached        close     broad     yellow  ...   
8108        attached        close     broad      brown  ...   
8109            free        close    narrow       buff  ...   
8110        attached        close     broad     yellow  ...   
8111            free      crowded     broad       gray  ...   

     Stalk-Surface-Above-Ring Stalk-Surface-Below-Ring Stalk-Color-Above-Ring  \
0                      smooth                   smooth                  white   
1                      smooth                   smooth                  white   
2                      smooth                   smooth                  white   
3                      smooth                   smooth                  white   
4                      smooth                   smooth                  white   
...                       ...                      ...                    ...   
8107                   smooth                   smooth                 orange   
8108                   smooth                   smooth                 orange   
8109                   smooth                    silky                  white   
8110                   smooth                   smooth                 orange   
8111                    silky                   smooth                  white   

     Stalk-Color-Below-Ring Veil-Color Ring-Number   Ring-Type  \
0                     white      white         one     pendant   
1                     white      white         one     pendant   
2                     white      white         one     pendant   
3                     white      white         one     pendant   
4                     white      white         one  evanescent   
...                     ...        ...         ...         ...   
8107                 orange      brown         one     pendant   
8108                 orange     orange         one     pendant   
8109                  white      white         one  evanescent   
8110                 orange     orange         one     pendant   
8111                  white      white         two     pendant   

     Spore-Print-Color Population  Habitat  
0                black  scattered    urban  
1                brown   numerous  grasses  
2                brown   numerous  meadows  
3                black  scattered    urban  
4                brown   abundant  grasses  
...                ...        ...      ...  
8107              buff    several   leaves  
8108              buff  clustered   leaves  
8109             white    several   leaves  
8110            orange  clustered   leaves  
8111             white  scattered  grasses  

[8112 rows x 22 columns]

In [31]:
mushroom.describe()

Class Cap-Shape Cap-Surface Cap-Color Bruises  Odor Gill-Attachment  \
count     8112      8112        8112      8112    8112  8112            8112   
unique       2         6           4        10       2     9               2   
top     edible    convex       scaly     brown      no  none            free   
freq      4196      3650        3244      2282    4736  3516            7904   

       Gill-Spacing Gill-Size Gill-Color  ... Stalk-Surface-Above-Ring  \
count          8112      8112       8112  ...                     8112   
unique            2         2         12  ...                        4   
top           close     broad       buff  ...                   smooth   
freq           6810      5600       1728  ...                     5169   

       Stalk-Surface-Below-Ring Stalk-Color-Above-Ring Stalk-Color-Below-Ring  \
count                      8112                   8112                   8112   
unique                        4                      9                      9   
top                      smooth                  white                  white   
freq                       4929                   4454                   4374   

       Veil-Color Ring-Number Ring-Type Spore-Print-Color Population Habitat  
count        8112        8112      8112              8112       8112    8112  
unique          4           3         5                 9          6       7  
top         white         one   pendant             white    several   woods  
freq         7914        7486      3956              2378       4040    3148  

[4 rows x 22 columns]

In [32]:
# our target is class so drop it in predictor variables

X = mushroom.drop('Class', axis=1)
y = mushroom[['Class']]

# Use to check that target variable is not in our predictor set and check predictor set is right
'Class' not in X.columns, 'Class' in y.columns

(True, True)

In [39]:
# split our data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

X_train

Cap-Shape Cap-Surface Cap-Color  Bruises   Odor Gill-Attachment  \
7337   knobbed       scaly       red       no  fishy            free   
8104   knobbed      smooth       red       no  fishy            free   
3123    convex       scaly       red  bruises   none            free   
7196   knobbed       scaly       red       no  fishy            free   
2996    convex       scaly     brown  bruises   none            free   
...        ...         ...       ...      ...    ...             ...   
5226    convex      smooth      gray  bruises   foul            free   
5390      flat      smooth      gray  bruises   foul            free   
860       flat       scaly     brown  bruises  anise            free   
7603      bell      smooth      gray       no   none            free   
7270   knobbed     fibrous      gray       no   none            free   

     Gill-Spacing Gill-Size Gill-Color Stalk-Shape  ...  \
7337        close    narrow       buff    tapering  ...   
8104        close    narrow       buff    tapering  ...   
3123        close     broad      brown    tapering  ...   
7196        close    narrow       buff    tapering  ...   
2996        close     broad      brown    tapering  ...   
...           ...       ...        ...         ...  ...   
5226        close     broad  chocolate    tapering  ...   
5390        close     broad       pink    tapering  ...   
860         close     broad      white   enlarging  ...   
7603      crowded     broad       gray   enlarging  ...   
7270      crowded     broad       gray   enlarging  ...   

     Stalk-Surface-Above-Ring Stalk-Surface-Below-Ring Stalk-Color-Above-Ring  \
7337                    silky                    silky                   pink   
8104                    silky                   smooth                   pink   
3123                   smooth                   smooth                  white   
7196                   smooth                   smooth                   pink   
2996                   smooth                   smooth                   gray   
...                       ...                      ...                    ...   
5226                  fibrous                   smooth                  white   
5390                   smooth                   smooth                  white   
860                    smooth                    scaly                  white   
7603                   smooth                   smooth                  white   
7270                    silky                    silky                  white   

     Stalk-Color-Below-Ring Veil-Color Ring-Number   Ring-Type  \
7337                  white      white         one  evanescent   
8104                  white      white         one  evanescent   
3123                   gray      white         one     pendant   
7196                  white      white         one  evanescent   
2996                   gray      white         one     pendant   
...                     ...        ...         ...         ...   
5226                  white      white         one     pendant   
5390                  white      white         one     pendant   
860                   white      white         one     pendant   
7603                  white      white         two     pendant   
7270                  white      white         two     pendant   

     Spore-Print-Color Population  Habitat  
7337             white    several   leaves  
8104             white    several    woods  
3123             black    several    woods  
7196             white    several    woods  
2996             black   solitary    woods  
...                ...        ...      ...  
5226         chocolate  scattered    urban  
5390         chocolate    several    urban  
860              brown   solitary    paths  
7603             white  scattered  grasses  
7270             white   numerous  grasses  

[6084 rows x 21 columns]

We are using a ordinal encoder even though the categories are not ordinal.
This is due to the fact that we will be using a tree model and tree models have a behavior
to perform well with ordinal encoders even when no ordering relationship is present
Also save time in not needing to perform one hot encoding and then pca

In [40]:
# we preprocess the training the data

ordinal_X = OrdinalEncoder()
X_train = ordinal_X.fit_transform(X_train)

ordinal_y = OrdinalEncoder()
y_train = ordinal_y.fit_transform((y_train))

display('X train', X_train, 'y train', y_train)

'X train'

array([[4., 2., 7., ..., 7., 4., 1.],
       [4., 3., 7., ..., 7., 4., 6.],
       [2., 2., 7., ..., 0., 4., 6.],
       ...,
       [3., 2., 0., ..., 1., 5., 3.],
       [0., 3., 3., ..., 7., 3., 0.],
       [4., 0., 3., ..., 7., 2., 0.]])

'y train'

array([[1.],
       [1.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [35]:
X_test

Cap-Shape Cap-Surface Cap-Color  Bruises   Odor Gill-Attachment  \
2157      flat     fibrous     brown  bruises   none            free   
453     convex     fibrous    yellow  bruises  anise            free   
8043    convex      smooth     brown       no   none        attached   
3985    convex     fibrous      gray       no   foul            free   
5366      flat       scaly    yellow       no   foul            free   
...        ...         ...       ...      ...    ...             ...   
6004    convex       scaly     white       no   none            free   
7941   knobbed       scaly     brown       no   foul            free   
5624      flat       scaly  cinnamon       no  musty        attached   
7991      bell      smooth     brown       no   none        attached   
1600    convex       scaly      gray  bruises   none            free   

     Gill-Spacing Gill-Size Gill-Color Stalk-Shape  ...  \
2157        close     broad     purple    tapering  ...   
453       crowded    narrow       pink    tapering  ...   
8043        close     broad      brown   enlarging  ...   
3985        close     broad       pink   enlarging  ...   
5366        close     broad       pink   enlarging  ...   
...           ...       ...        ...         ...  ...   
6004        close    narrow      white   enlarging  ...   
7941        close    narrow       buff    tapering  ...   
5624        close     broad      white   enlarging  ...   
7991        close     broad      brown   enlarging  ...   
1600        close     broad      brown    tapering  ...   

     Stalk-Surface-Above-Ring Stalk-Surface-Below-Ring Stalk-Color-Above-Ring  \
2157                   smooth                   smooth                  white   
453                    smooth                   smooth                  white   
8043                   smooth                   smooth                 orange   
3985                    silky                    silky                   pink   
5366                    silky                    silky                   pink   
...                       ...                      ...                    ...   
6004                   smooth                  fibrous                  white   
7941                    silky                   smooth                   pink   
5624                    silky                    scaly               cinnamon   
7991                   smooth                   smooth                 orange   
1600                   smooth                   smooth                   pink   

     Stalk-Color-Below-Ring Veil-Color Ring-Number   Ring-Type  \
2157                   gray      white         one     pendant   
453                   white      white         one     pendant   
8043                 orange      brown         one     pendant   
3985                  brown      white         one       large   
5366                   buff      white         one       large   
...                     ...        ...         ...         ...   
6004                  white      white         one     flaring   
7941                  white      white         one  evanescent   
5624               cinnamon      white        none        none   
7991                 orange     orange         one     pendant   
1600                   gray      white         one     pendant   

     Spore-Print-Color Population  Habitat  
2157             brown    several    woods  
453              brown    several    woods  
8043             brown    several   leaves  
3985         chocolate   solitary  grasses  
5366         chocolate    several    woods  
...                ...        ...      ...  
6004         chocolate    several    woods  
7941             white    several    paths  
5624             white  clustered    woods  
7991             brown  clustered   leaves  
1600             black   solitary    woods  

[2028 rows x 21 columns]

In [36]:
# preprocess the test data

X_test = ordinal_X.transform(X_test)

y_test = ordinal_y.transform(y_test)

display('X test', X_test, 'y test', y_test)

'X test'

array([[3., 0., 0., ..., 1., 4., 6.],
       [2., 0., 9., ..., 1., 4., 6.],
       [2., 3., 0., ..., 1., 4., 1.],
       ...,
       [3., 2., 2., ..., 7., 1., 6.],
       [0., 3., 0., ..., 1., 1., 1.],
       [2., 2., 3., ..., 0., 5., 6.]])

'y test'

array([[0.],
       [0.],
       [0.],
       ...,
       [1.],
       [0.],
       [0.]])

In [37]:
# save these preprocessed values for usage on modeling

# savez saves these as compressed files
np.savez('../../data/processed/train.npz', X_train, y_train)
np.savez('../../data/processed/test.npz', X_test, y_test)

In [38]:
# Save our transformers

joblib.dump(ordinal_X, '../../data/processed/ordinal_X')
joblib.dump(ordinal_y, '../../data/processed/ordinal_y')

['../../data/processed/ordinal_y']